### ISSUE TITLE
GPT 모델 연결 및 파일 저장

### ISSUE THREAD

**Issue by ej20001000** [receiptAutoScan/receipt-backend#49]
## Description:
GPT 모델과 연결하여 통신
파일 저장 후 처리

## To-Do:
- [x] controller 내 post mapping
- [x] service 로직 구현
- [x] save file logic
