### ISSUE TITLE
MongoDB 사용하여 챗봇 로그 저장

### ISSUE THREAD

**Issue by ej20001000** [receiptAutoScan/receipt-backend#52]
## Description:
MongoDB를 사용하여 챗봇 로그를 저장 합니다

## To-Do:
- [ ] MongoDB 설치 및 설정
- [ ] Spring boot application과 연동
- [ ] 챗봇 로깅 로직 구현
